export const properties = [
  {
    id: 1,
    date: "1404/07/20",
    itemName: "داروی سرماخوردگی",
    unit: "بسته",
    minQuantity: "10",
    tracker: "علی رضایی",
    description: "دارو برای بخش اطفال خریداری شده است.",
  },
  {
    id: 2,
    date: "1404/07/21",
    itemName: "دستکش طبی",
    unit: "جفت",
    minQuantity: "50",
    tracker: "سارا احمدی",
    description: "برای استفاده در بخش جراحی تهیه گردید.",
  },
  {
    id: 3,
    date: "1404/07/22",
    itemName: "ماسک تنفسی",
    unit: "عدد",
    minQuantity: "100",
    tracker: "حمید نورزی",
    description: "در انبار اصلی ذخیره شده است.",
  },
  {
    id: 4,
    date: "1404/07/23",
    itemName: "محلول ضدعفونی",
    unit: "لیتر",
    minQuantity: "20",
    tracker: "فرشته حسینی",
    description: "برای ضدعفونی اتاق‌ها استفاده می‌شود.",
  },
  {
    id: 5,
    date: "1404/07/24",
    itemName: "پنبه طبی",
    unit: "بسته",
    minQuantity: "15",
    tracker: "مجید کریمی",
    description: "مقدار جدید به انبار افزوده شد.",
  },
];
